baseurl = "https://www.drplatoni.com"
title = "Dr. Kathy Platoni"
languageCode = "en-us"
preserveTaxonomyNames = true

[pagination]
  pagerSize = 5

[params]
  SEOTitle = "Dr. Kathy Platoni | Clinical Psychologist, Trauma & PTSD Expert"
  description = "Dr. Kathy Platoni, Psy.D., DAAPM, FAIS – Expert in Healing Trauma, Combat Stress, and Mass Casualties. Author, Speaker, Trainer, and Clinical Psychologist based in Centerville, Ohio."
  keyword = "Dr. Kathy Platoni, Trauma, PTSD, Combat Stress, Clinical Psychologist, Ohio Veterans, Speaker, Trainer, Author"
